import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainHeader from "@/component/main-header"
import Footer from "@/component/main-footer";
import ClientLayout from "@/component/clientLayout";
import { AuthProvider } from "@/context/authContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        
        <AuthProvider>
        <ClientLayout>
         {children}
         </ClientLayout>
         </AuthProvider>
         
      </body>
    </html>
  );
}
